In [4]:
import pandas as pd

In [5]:
!pip install openpyxl

Requirement already satisfied: openpyxl in ./.pyenv/versions/3.10.11/lib/python3.10/site-packages (3.1.2)
Requirement already satisfied: et-xmlfile in ./.pyenv/versions/3.10.11/lib/python3.10/site-packages (from openpyxl) (1.1.0)

[notice] A new release of pip is available: 23.0.1 -> 23.1.2
[notice] To update, run: pip install --upgrade pip

In [10]:
pd.read_excel('001051370.xlsx')
df= pd.read_excel('001051370.xlsx')

In [11]:
df

,Unnamed: 0,性別・年齢階級別、自殺者数詳細（職業）,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 105,Unnamed: 106,Unnamed: 107,Unnamed: 108,Unnamed: 109,Unnamed: 110,Unnamed: 111,Unnamed: 112,Unnamed: 113,Unnamed: 114
0,NaN,令和4年暫定値,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,（発見日）,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,職業,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,有職,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,自殺者数,有職総計,管理的職業従事者総計,議員・知事・課長以上の公務員,...,失業者（離職時期不明）,利子・配当・家賃等生活者,年金受給者（老齢・遺族給付）,年金受給者（障害給付）,雇用保険受給者,生活保護受給者,ホームレス,その他の無職者（ひきこもり）,その他の無職者（ひきこもり以外）,職業不詳
6,NaN,全国,計,NaN,NaN,計,21843,8540,1430,39,...,225,52,4710,495,46,797,19,881,2346,481
7,NaN,NaN,NaN,NaN,NaN,男,14722,6784,1272,36,...,182,40,2921,275,33,494,19,624,1487,368
8,NaN,NaN,NaN,NaN,NaN,女,7121,1756,158,3,...,43,12,1789,220,13,303,0,257,859,113
9,NaN,NaN,NaN,～19歳,NaN,計,798,94,1,0,...,1,0,0,1,0,2,0,24,38,2
10,NaN,NaN,NaN,NaN,NaN,男,465,67,1,0,...,0,0,0,0,0,0,0,11,18,1
11,NaN,NaN,NaN,NaN,NaN,女,333,27,0,0,...,1,0,0,1,0,2,0,13,20,1
12,NaN,NaN,NaN,20～29歳,NaN,計,2479,1272,45,2,...,24,1,1,40,2,45,1,173,308,65
13,NaN,NaN,NaN,NaN,NaN,男,1671,905,36,0,...,16,1,0,22,2,18,1,124,175,39
14,NaN,NaN,NaN,NaN,NaN,女,808,367,9,2,...,8,0,1,18,0,27,0,49,133,26
15,NaN,NaN,NaN,30～39歳,NaN,計,2540,1492,136,4,...,33,1,1,71,3,85,2,192,324,66
16,NaN,NaN,NaN,NaN,NaN,男,1782,1162,118,4,...,23,1,1,32,2,45,2,137,200,53
17,NaN,NaN,NaN,NaN,NaN,女,758,330,18,0,...,10,0,0,39,1,40,0,55,124,13
18,NaN,NaN,NaN,40～49歳,NaN,計,3660,2137,330,9,...,57,3,8,119,7,143,2,203,421,79
19,NaN,NaN,NaN,NaN,NaN,男,2604,1711,292,9,...,51,3,4,63,5,71,2,150,261,65
20,NaN,NaN,NaN,NaN,NaN,女,1056,426,38,0,...,6,0,4,56,2,72,0,53,160,14
21,NaN,NaN,NaN,50～59歳,NaN,計,4088,2117,438,19,...,75,10,24,106,16,205,7,199,540,106
22,NaN,NaN,NaN,NaN,NaN,男,2841,1733,394,18,...,62,8,14,62,12,123,7,136,343,80
23,NaN,NaN,NaN,NaN,NaN,女,1247,384,44,1,...,13,2,10,44,4,82,0,63,197,26
24,NaN,NaN,NaN,60～69歳,NaN,計,2757,928,256,4,...,24,15,687,71,7,116,4,66,361,64
25,NaN,NaN,NaN,NaN,NaN,男,1857,788,239,4,...,21,10,421,47,5,82,4,50,257,52
26,NaN,NaN,NaN,NaN,NaN,女,900,140,17,0,...,3,5,266,24,2,34,0,16,104,12
27,NaN,NaN,NaN,70～79歳,NaN,計,2990,399,170,1,...,8,15,1957,45,6,142,2,16,204,35
28,NaN,NaN,NaN,NaN,NaN,男,1905,327,144,1,...,7,12,1211,26,4,116,2,12,138,26
29,NaN,NaN,NaN,NaN,NaN,女,1085,72,26,0,...,1,3,746,19,2,26,0,4,66,9
30,NaN,NaN,NaN,80歳～,NaN,計,2480,101,54,0,...,3,7,2032,42,5,59,1,8,150,14
31,NaN,NaN,NaN,NaN,NaN,男,1555,91,48,0,...,2,5,1270,23,3,39,1,4,95,10
32,NaN,NaN,NaN,NaN,NaN,女,925,10,6,0,...,1,2,762,19,2,20,0,4,55,4
33,NaN,NaN,NaN,不詳,NaN,計,51,0,0,0,...,0,0,0,0,0,0,0,0,0,50
34,NaN,NaN,NaN,NaN,NaN,男,42,0,0,0,...,0,0,0,0,0,0,0,0,0,42
35,NaN,NaN,NaN,NaN,NaN,女,9,0,0,0,...,0,0,0,0,0,0,0,0,0,8